_target_: pytorch_lightning.Trainer

gpus                  : 1
min_epochs            : 1
max_epochs            : 40
auto_lr_find          : False
terminate_on_nan      : True
auto_scale_batch_size : False
gradient_clip_val     : 1.0
reload_dataloaders_every_epoch: True
weights_summary               : null
progress_bar_refresh_rate     : 10
resume_from_checkpoint        : ${PATH.checkpoint}