# @package _global_

##################################
## GENERAL CONFIGURATIONS
##################################
work_dir: ${hydra:runtime.cwd}
data_dir: ${work_dir}/data/
print_config: True
ignore_warnings: True
optimized_metric: "valid/rouge_l"
hydra:
  run:
    dir: logs/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    storage: null
    study_name: null
    n_jobs: 1

    # 'minimize' or 'maximize' the objective
    direction: maximize

    # number of experiments that will be executed
    n_trials: 20

    # choose Optuna hyperparameter sampler
    # learn more here: https://optuna.readthedocs.io/en/stable/reference/samplers.html
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 307
      consider_prior: true
      prior_weight: 1.0
      consider_magic_clip: true
      consider_endpoints: false
      n_startup_trials: 10
      n_ei_candidates: 24
      multivariate: false
      warn_independent_sampling: true

    # define range of hyperparameters
    search_space:
      model.lr:
        type: float
        low: 1e-5
        high: 0.2
      model.warmup_rate:
        type: float
        low: 0.1
        high: 0.3
        step: 0.05
      model.w_decay:
        type: float
        low: 0.01
        high: 0.95
        step: 0.1
      batch_size:
        type: categorical
        choices: [4, 5, 8]

defaults:
  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog
  - override /hydra/sweeper: optuna

##################################
## CONFIGURATIONS for components
##################################
PATH:
  utils: ""
  pretrained: ${PATH.utils}/bert-base-uncased
  data: ${PATH.utils}/processed/story/[SPLIT]/data_[SHARD].parquet
  last_best: ${work_dir}/logs/last_best.ckpt

mode: train
# There are 4 modes: train, predict, debug_train, debug_predict

batch_size: 5
n_workers: 8
n_shards: 4

l_q: 33
n_c: 10 # total number of reviews
l_c: 178
l_a: 10
sizes_dataset:
  train: 32747
  test: 10557
  valid: 3461

trainer:
  _target_: pytorch_lightning.Trainer
  gpus: 1
  min_epochs: 1
  max_epochs: 30
  auto_lr_find: False
  precision: 16
  terminate_on_nan: True
  log_every_n_steps: 40
  auto_scale_batch_size: False
  gradient_clip_val: 1.0
  check_val_every_n_epoch: 1
  reload_dataloaders_every_epoch: True
  weights_summary: "top"
  progress_bar_refresh_rate: 5
  resume_from_checkpoint: ${PATH.last_best}

model:
  _target_: models.chime_model.CHIMELitModel
  batch_size: ${batch_size}
  l_a: ${l_a}
  path_pretrained: ${PATH.pretrained}
  path_valid_pred: ${work_dir}/logs/valid_pred.json
  size_dataset_train: ${sizes_dataset.train}
  max_epochs: ${trainer.max_epochs}
  warmup_rate: 0.2
  lr: 1e-5
  w_decay: 0.95

datamodule:
  _target_: datamodules.chime_datamodule.CHIMEDataModule
  batch_size: ${batch_size}
  sizes_dataset: ${sizes_dataset}
  path_data: ${PATH.data}
  l_c: ${l_c}
  n_c: ${n_c}
  n_shards: ${n_shards}

callbacks:
  ModelCheckpoint:
    _target_: pytorch_lightning.callbacks.ModelCheckpoint
    monitor: "valid/rouge_l"
    save_top_k: 2
    save_last: True
    mode: "max"
    dirpath: "chkpts/"
    filename: "chime-{epoch:02d}"
  LearningRateMonitor:
    _target_: pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: step
  # EarlyStopping:
  #   _target_: pytorch_lightning.callbacks.EarlyStopping
  #   monitor: valid/bleu_1
  #   min_delta: 0.001
  #   patience: 4
  #   verbose: False
  #   mode: max

logger:
  tensorboard:
    _target_: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
    save_dir: "tensorboard/"
    name: "default"
    version: null
    log_graph: False
    default_hp_metric: True
    prefix: ""
  wandb:
    _target_: pytorch_lightning.loggers.wandb.WandbLogger
    project: "narrative-chime"
    name: ${now:%A %b-%d %H:%M}
    save_dir: "."
    offline: False # set True to store all logs only locally
    id: null # pass correct id to resume experiment!
    # entity: ""  # set to name of your wandb team or just remove it
    log_model: False
    prefix: ""
    job_type: "train"
    group: ""
    tags: []
