# @package _global_

##################################
## GENERAL CONFIGURATIONS
##################################
work_dir: ${hydra:runtime.cwd}
data_dir: ${work_dir}/data/
print_config: True
ignore_warnings: True
hydra:
  run:
    dir: logs/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

##################################
## CONFIGURATIONS for components
##################################
PATH:
  utils: ""
  pretrained: ${PATH.utils}/bert-base-uncased
  data: ${PATH.utils}/story/[SPLIT]/data_[SHARD].parquet
  log: ${work_dir}/logs

mode: train

batch_size: 5
n_workers: 4
n_shards: 4

##########################################
###### CONFIGURATIONS FOR EACH COMPONENT
##########################################
l_q: 35
l_c: 180
l_a: 12
n_c: 10

trainer:
  gpus: 1
  min_epochs: 1
  max_epochs: 100
  auto_lr_find: False
  terminate_on_nan: True
  log_every_n_steps: 40
  auto_scale_batch_size: False
  gradient_clip_val: 1.0
  accelerator: null
  precision: 16
  check_val_every_n_epoch: 1
  reload_dataloaders_every_epoch: True
  weights_summary: "top"
  progress_bar_refresh_rate: 5
  resume_from_checkpoint: ${PATH.log}/last_best.ckpt

model:
  batch_size: ${batch_size}
  l_q: ${l_q}
  l_c: ${l_c}
  l_a: ${l_a}
  n_c: ${n_c}
  n_heads: 4
  d_hid: 64
  d_bert: 768
  d_vocab: 30522
  lr: 1e-5
  w_decay: 1e-2
  dropout: 0.2
  beam_size: 20
  n_gram_beam: 8
  path_pretrained: ${PATH.pretrained}
  path_pred: ${PATH.log}/pred.json
  path_train_pred: ${PATH.log}/train_pred.json
  path_valid_pred: ${PATH.log}/valid_pred.json

datamodule:
  batch_size: ${batch_size}
  sizes_dataset:
    train: 32747
    test: 10557
    valid: 3461
  l_c: ${l_c}
  n_c: ${n_c}
  n_shards: ${n_shards}
  path_data: ${PATH.data}

callbacks:
  ModelCheckpoint:
    _target_: pytorch_lightning.callbacks.ModelCheckpoint
    monitor: "valid/loss"
    save_top_k: 2
    save_last: True
    mode: "min"
    dirpath: ${PATH.log}/tensorboard/ckpts/
    filename: "narrative_weam-{epoch:02d}"
  # EarlyStopping:
  #   _target_: pytorch_lightning.callbacks.EarlyStopping
  #   monitor: valid/bleu_1
  #   min_delta: 0.001
  #   patience: 4
  #   verbose: False
  #   mode: max

logger:
  tensorboard:
    _target_: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
    save_dir: ${PATH.log}/tensorboard/
    name: default
    version: null
    log_graph: False
    default_hp_metric: False
  wandb:
    _target_: pytorch_lightning.loggers.wandb.WandbLogger
    project: "narrative_graph"
    name: narrative_weam-${now:%b-%d:%H-%M}
    save_dir: "."
    offline: False # set True to store all logs only locally
    id: null # pass correct id to resume experiment!
    # entity: ""  # set to name of your wandb team or just remove it
    log_model: False
    prefix: ""
    job_type: "train"
    group: ""
    tags: []
