_target_: src.models.narrative_model.NarrativeModel

seq_len_ques: 42
seq_len_para: 122
seq_len_ans : 42
n_paras     : 30
n_layers_gru: 5
n_layers_trans: 3
n_heads_trans : 4
max_len_ans : 12
d_hid       : 64
d_bert      : 768
d_vocab     : 32716
lr          : 5e-4
w_decay     : 0.0005
beam_size   : 20
n_gram_beam : 8
temperature : 1.4

path_bert   : ${PATH.bert}
path_vocab  : ${PATH.vocab}
path_pred   : ${PATH.pred}
path_train_pred: ${PATH.train_pred}