_target_: src.models.narrative_model.NarrativeModel

batch_size: ${batch_size}
l_q: 42
l_c: 170
l_a: 1
n_nodes: 10
n_edges: 40
n_gru_layers: 5
d_hid: 64
d_bert: 768
d_vocab: 30522
d_graph: 2048
precision: 16
lr: 1e-5
w_decay: 1e-2
switch_frequency: 5
beam_size: 20
n_gram_beam: 8
temperature: 1.4
topP: 0.5

path_train_pred: ${PATH.train_pred}
path_valid_pred: ${PATH.valid_pred}
