_target_: src.models.narrative_model.NarrativeModel

batch_size  : ${batch_size}
seq_len_ques: 42
seq_len_para: 122
seq_len_ans : 42
n_nodes     : 435
n_edges     : 3120
n_gru_layers: 5
max_len_ans : 12
d_hid       : 64
d_bert      : 768
d_vocab     : 32716
d_graph     : 2048
lr          : 5e-4
w_decay     : 0.0005
beam_size   : 20
n_gram_beam : 8
temperature : 1.4
topP        : 0.5

path_bert   : ${PATH.bert}
path_vocab  : ${PATH.vocab}
path_pred   : ${PATH.pred}
path_train_pred: ${PATH.train_pred}