model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: "valid/loss"
  save_top_k: 2
  save_last: True
  mode: "min"
  dirpath: "checkpoints/"
  filename: "narrative-{epoch:02d}"
