_target_: src.datamodules.narrative_datamodule.NarrativeDataModule

batch_size: ${batch_size}
num_workers: ${num_workers}
num_shards: ${num_shards}
len_ques: 42
len_para: 170
len_para_processing: 120
len_ans: 15
sizes_dataset:
  train: 32747
  test: 10557
  valid: 3461
