_target_: src.datamodules.narrative_datamodule.NarrativeDataModule

batch_size: ${batch_size}
num_workers: ${num_workers}
seq_len_ques: 42
seq_len_para: 170
seq_len_ans: 15
len_para_processing: 150
sizes_dataset:
  train: 32747
  test: 10557
  valid: 3461

path_bert: ${PATH.bert}
path_data: ${PATH.data}
path_raw_data: ${PATH.raw_data}
path_processed_contx: ${PATH.processed_contx}
