_target_: src.datamodules.narrative_datamodule.NarrativeDataModule

batch_size: ${batch_size}
num_workers: ${num_workers}
seq_len_ques: 42
seq_len_para: 182
len_para_processing: 120
seq_len_ans: 42
sizes_dataset:
  train: 32744
  test: 10552
  valid: 3456
sizes_shard:
  train: 4093
  test: 1319
  valid: 432

path_bert: ${PATH.vocab}
path_data: ${PATH.data}
path_raw_data: ${PATH.raw_data}
path_processed_contx: ${PATH.processed_contx}
