_target_: src.datamodules.narrative_datamodule.NarrativeDataModule

batch_size: ${batch_size}
num_workers: ${num_workers}
l_q: 42
l_c: 170
l_a: 15
l_c_processing: 150
sizes_dataset:
  train: 32747
  test: 10557
  valid: 3461
